name: Compline Reminder

on:
  schedule:
    # Run daily at 1:00 PM UTC (9:00 PM Singapore time, UTC+8)
    - cron: '0 13 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-compline-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send Compline Reminder
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_MESSAGE_THREAD_ID: ${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}
      run: |
        python poll_bot.py --send-reminder
    
    - name: Log completion
      run: |
        echo "✅ Catholic_DO_Completorium_Bot reminder executed at $(date) (9 PM Singapore time)"
